server:
  port: 8082

spring:
  # Multipart File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 2KB

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/campus_connect_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgres
      mode: always
      data-locations: classpath:comitte-data.sql,classpath:campus-connect-data.sql
      defer-datasource-initialization: true
      continue-on-error: false
      separator: ;
      encoding: UTF-8

  # JPA/Hibernate Configuration
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop # none/validate/update/create/create-drop/use 'validate' in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: rajauravikas@gmail.com
    password: "pppc hinx amnt huxq"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: Pqhv2J9XBNyQIHFDdYih5xSwp6hE9XN6ropqZIpzqE6wByLy8xqyrWGXm1T2pkKfbKTDgy2go4b12aiQsD8wdQ==
  expiration-ms: 360000000

email:
  password-reset-email-subject: "Password Reset"
  password-reset-email-body: "To reset your password, click the link below:\n {0} \n       or \n Enter otp: {1}"
  password-reset-token-expiry: 5

# File Upload Configuration
file:
  upload:
    upload-dir: uploads
    max-file-size: 5242880  # 5MB in bytes
    allowed-extensions: jpg,jpeg,png,gif

# ---------------------------------------------------
# --- SpringDoc (Swagger) OpenAPI 3 Configuration ---
# ---------------------------------------------------
springdoc:
  # Custom path for the Swagger UI
  swagger-ui:
    path: /swagger-ui.html
  # Path for the API documentation in JSON format
  api-docs:
    path: /api-docs
  # General API information
  info:
    title: "Comitte Application API"
    description: "API documentation for the Comitte application."
    version: "v1.0.0"
    contact:
      name: "API Support Team"
      email: "support@example.com"

logging:
  level:
    com.ls: DEBUG # Sets the log level to DEBUG for your application's packages
    org.springframework.web: DEBUG # Sets the log level to INFO for Spring Web classes
    org.springframework.boot.autoconfigure.sql.init: DEBUG # SQL init debugging
    org.springframework.jdbc: DEBUG # JDBC debugging for SQL init
    org.hibernate: ERROR # Sets the log level to ERROR for Hibernate (JPA)
